nodeLinker: node-modules

plugins:
  - checksum: c43fb18b0cc042871a14ddc76ec78d35b4bc6896ec1d2b75d137cfc6b6b3e2a83fe6cb8b1d2657700b460e81d843b8dc33c5330db1cce2cffe2d91ce0442eb14
    path: .yarn/plugins/@yarnpkg/plugin-dedupe.cjs
    spec: "https://github.com/blimmer/yarn-plugin-dedupe/releases/download/v1.0.0/plugin-dedupe.js"
