title: Ben Limmer
tagline: "Software Engineer and Architect"
author:
  name: Ben Limmer
  email: hello@benlimmer.com
  github: blimmer
  keybase: blimmer
description:
  "A software engineering blog written by Ben Limmer. Topics include EmberJS, software development best-practices,
  automated testing and more."

url: https://benlimmer.com
production_url: https://benlimmer.com
permalink: pretty
timezone: America/Denver

defaults:
  - scope:
      path: "" # empty string for all files
      type: posts # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
  - scope:
      path: "assets/**/*"
    values:
      sitemap: false

exclude:
  - deploy.sh
  - LICENSE
  - README

plugins:
  - jekyll/minibundle
  - jekyll-octicons
  - jekyll-sitemap
  - jekyll-last-modified-at
