permalink: /:categories/:year/:month/:day/:title

title : Ben Limmer
tagline: "Software Developer in Denver, Colorado, USA"
author :
  name : Ben Limmer
  email : hello@benlimmer.com
  github : blimmer
  twitter : l1m5
  googleplus: +BenLimmer

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
