title: Ben Limmer
tagline: "Freelance Architect and Software Engineer"
author:
  name: Ben Limmer
  email: hello@benlimmer.com
  github: blimmer
  keybase: blimmer
description:
  "Ben Limmer is a freelance architect specializing in Developer Tools & Experience, Cloud Computing, Front-End and
  Back-End Development and speaking engagements."

url: https://benlimmer.com
production_url: https://benlimmer.com
permalink: pretty
timezone: America/Denver

defaults:
  - scope:
      path: "" # empty string for all files
      type: posts # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
  - scope:
      path: "assets/**/*"
    values:
      sitemap: false

exclude:
  - deploy.sh
  - LICENSE
  - README

plugins:
  - jekyll/minibundle
  - jekyll-octicons
  - jekyll-sitemap
  - jekyll-last-modified-at
